version: "3.7"

services:

  api:
    build:
      context: ./api
    # Expose the api service on localhost:8080,
    # so you can test it from your machine as well.
    ports:
      - "8080:8080"

  test:
    build:
      context: ./test
    environment:
      API_URL: "http://api:8080"
    command: dockerize -wait http://api:8080 npm test
